version: '3.1'

services:
  neo4j:
    image: neo4j:3.5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo

  node:
    image: node-crawler
    build:
      context: services/node
    volumes:
      - ./services/node/src:/usr/src/app/src

  golang:
    image: golang-crawler
    build:
      context: services/golang
    volumes:
      - ./services/golang/src:/usr/src/app/src
    depends_on:
      - neo4j
    command: go run src/main.go ${WEBSITE}
